repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.0
    hooks:
      - id: pyupgrade
        args: ["--py39-plus"]

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies: [pep8-naming]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-byte-order-marker

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: "v8.16.0"
    hooks:
      - id: eslint
        files: \.[jt]s?$
        types: [file]
        exclude: live\S*\.ts
        additional_dependencies:
          - eslint@latest
          - "@typescript-eslint/eslint-plugin@latest"
          - "@typescript-eslint/parser@latest"
          - "eslint-plugin-cypress@latest"
  # - repo: local
  #   hooks:
  #     - id: eslint
  #       name: eslint
  #       entry: bash -c "cd webapp && npm run lint"
  #       language: node
  #       files: \.[jt]s?$
  #       types: [file]
  #       additional_dependencies:
  #         - eslint@latest
  #         - "@typescript-eslint/eslint-plugin@latest"
  #         - "@typescript-eslint/parser@latest"
  #         - "eslint-plugin-cypress@latest"
