version: '3.8'

x-common-variables: &api-common-variables
  S3_LABELED_PATH: s3://acoustic-sandbox/orcaal-dev/labeled_test/
  S3_UNLABELED_PATH: s3://acoustic-sandbox/orcaal-dev/unlabeled_test/
  RETRAIN_TARGET: 20
  S3_MODEL_PATH: s3://acoustic-sandbox/orcaal-dev/models/srkw_0.h5
  IMG_WIDTH: 607
  IMG_HEIGHT: 617
  EPOCHS: 1
  DATABASE_URL: postgresql+psycopg2://postgres:password@dbserver/orcagsoc
  ML_ENDPOINT_URL: http://ml:5001

services:
  ml-endpoint-dev:
    image: ml-endpoint-dev
    container_name: ml-endpoint-dev
    restart: on-failure
    build:
      context: ./train_and_predict
      dockerfile: Dockerfile
      target: dev
    environment:
      AWS_ACCESS_KEY_ID: AKIAZN2WCXIFT2PS3XEI
      AWS_SECRET_ACCESS_KEY: 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
      AWS_REGION: eu-west-1
    ports:
      - 5001:5001
    volumes:
      - ./train_and_predict:/orcagsoc

  postgres-dev:
    image: postgres
    container_name: postgres-dev
    restart: on-failure
    environment:
      POSTGRES_DB: orcagsoc
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 10s

  api-endpoint-dev:
    image: api-endpoint-dev
    container_name: api-endpoint-dev
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
      target: dev
    restart: on-failure
    links:
      - postgres-dev:dbserver
      - ml-endpoint-dev:ml
    environment: *api-common-variables
    depends_on:
      postgres-dev:
        condition: service_healthy
      ml-endpoint-dev: 
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "-f", "http://host-gateway:5000/statistics"]
      interval: 15s
      timeout: 3s
      retries: 8
      start_period: 30s
    ports:
      - 5000:5000
    volumes:
      - ./api:/orcagsoc

  webapp-dev:
    image: webapp-dev
    container_name: webapp-dev
    restart: on-failure
    build:
      context: ./webapp
      dockerfile: Dockerfile
      target: dev
    ports:
      - 8080:8080
    depends_on:
      api-endpoint-dev:
        condition: service_healthy 
    volumes:
      - ./webapp:/webapp
